# Generated by Django 3.1.1 on 2020-11-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookpubl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Name:'),
        ),
    ]
