# Generated by Django 3.1.1 on 2020-11-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookpubl', '0002_auto_20201104_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gen',
            field=models.IntegerField(choices=[(1, 'Adventures'), (2, 'Romance'), (3, 'Detective'), (4, 'Horror')], verbose_name='Genre:'),
        ),
    ]
